import type { Metadata } from 'next';
import { Saira, Saira_Stencil_One } from 'next/font/google';
import './globals.css';

const saira = Saira({
  variable: '--font-saira',
  subsets: ['latin'],
});

const sairaStencil = Saira_Stencil_One({
  variable: '--font-saira-stencil',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${saira.variable} ${sairaStencil.variable} antialiased`}>{children}</body>
    </html>
  );
}
